train: data/train/
val: data/valid/
save_path: results/
model : vit_l_16
weights: None
batch_size: 8
image_size: 224
num_classes: 5
class_names: [
        'DJIMAVIC3PRO',
        'DJIFPVCOMBO',
        'DJIMINI3',
        'DJIMINI4PRO',
        'DJIAVATA2'
]
device: 'cuda'
num_epochs: 150
shuffle: True
lr: 0.00001
optimizer: None

